# version format
version: 1.0.0.{build}

# to run your custom scripts instead of automatic MSBuild
install:
  - cmd: cd BuildPackage
  - cmd: Build.bat

# to disable automatic builds
build: off

artifacts:
  - path: BuildPackage\Package\*.nupkg
  - path: BuildPackage\Package\*.zip